[package]
name = "sreymara_vault"
version = "0.1.0"
description = "Sreymara 80/20 On-Chain Revenue Sharing and Vault Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sreymara_vault"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
